# Copyright (c) 2025 STMicroelectronics
# All rights reserved.
#
# This software is licensed under terms that can be found in the LICENSE file
# in the root directory of this software component.
# If no LICENSE file comes with this software, it is provided AS-IS.

CONFIG_MY_APP=y
CONFIG_MAIN_STACK_SIZE=8192
# CONFIG_XIP is not set
CONFIG_USE_STM32_MW_ISP=y
CONFIG_DYNAMIC_INTERRUPTS=y
CONFIG_FLASH=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_LOG=y
# Temporary disable assertions due to https://github.com/zephyrproject-rtos/zephyr/issues/97904
CONFIG_ASSERT=n
CONFIG_CONSOLE=y
CONFIG_LV_CONF_MINIMAL=y
CONFIG_LV_USE_CANVAS=y
CONFIG_LV_USE_THEME_DEFAULT=y
CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=8192
CONFIG_ARM_MPU=y
# CONFIG_THREAD_MONITOR is not set
# CONFIG_THREAD_NAME is not set
CONFIG_UART_CONSOLE=y
CONFIG_DISPLAY=y
CONFIG_STM32_MEMMAP=y
CONFIG_VIDEO=y
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=4
CONFIG_VIDEO_STM32_DCMIPP_SENSOR_WIDTH=2592
CONFIG_VIDEO_STM32_DCMIPP_SENSOR_HEIGHT=1944
CONFIG_VIDEO_STM32_DCMIPP_SENSOR_PIXEL_FORMAT="pRAA"
CONFIG_MULTI_HEAP=y
CONFIG_CPU_LOAD=y
CONFIG_MEM_ATTR_HEAP=y
# To be sure LOGGER can still ouput message move this one priority level above main thread
CONFIG_LOG_PROCESS_THREAD_CUSTOM_PRIORITY=y
CONFIG_LOG_PROCESS_THREAD_PRIORITY=13
CONFIG_LV_FONT_UNSCII_16=y
